version: "3.1"

services:
  be:
    build:
      context: springboot-firebase-auth
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .secrets/firebase-config.json:/.secrets/firebase-config.json
    environment:
      # - APP_FIREBASE_CREDENTIAL_PATH=/.secrets/firebase-config.json
      - GOOGLE_APPLICATION_CREDENTIALS=/.secrets/firebase-config.json
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dev-db
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=aPPp@Ss
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    networks:
      - be

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r0oTp@ss
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: aPpP@Ss
    ports:
      - 3306:3306
    networks:
      - be

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - be

  fe:
    build:
      context: react-firebase-auth
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - fe

networks:
  be:
  fe:
